version: '3'
services:
  redis:
    restart: always
    container_name: redis
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379
  redis-exporter:
    restart: always
    image: oliver006/redis_exporter:v1.45.0-alpine
    container_name: redis-exporter
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://redis-server:6379'
      # - '--redis.password=slightly-locked'
      
