version: '3.7'
services:
  jenkins:
    image: jenkinsci/blueocean:1.24.6-bcc31d32159f
    privileged: true
    user: root
    ports:
      - 8083:8080
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock