# ref: https://github.com/khezen/compose-postgres
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    hostname: your-name
    labels:
      appName: NathanLu
      gender: female
      hostname: test
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.1.25:12201"
        # docker run --rm --name test --label appName=NathanLu --label gender=male --label slogan=seagon --log-opt labels=appName,gender,slogan --log-driver=gelf --log-opt gelf-address=udp://192.168.1.25:12201 -d busybox sh -c "while true; do $(echo date); sleep 1; done"
        labels: appName,gender,hostname

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
