web:
  build: .
  links:
    - db
  ports:
    - 80:80
  volumes:
    - ./www/html:/var/www/html

db:
  image: mysql:latest
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
  ports:
    - 8887:3306