version: '3'

services:
  emqx:
    image: emqx:5.0.20
    container_name: emqx
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    volumes:
      - ./data:/opt/emqx/data

# username: admin password: public