version: '3'
services:
    myvault:
        image: vault
        container_name: vault-server
        ports:
          - "8200:8200"
        volumes:
          - ./file:/vault/file
          - ./config:/vault/config
        environment:
          - VAULT_ADDR=http://0.0.0.0:8200
          - VAULT_API_ADDR=http://0.0.0.0:8200
          - VAULT_ADDRESS=http://0.0.0.0:8200
        cap_add:
          - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json