version: '3'
services:
  registry:
    image: registry
    restart: always
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
        - 8080:80
    volumes:
        - ./frontend/certs/frontend.crt:/etc/apache2/server.crt:ro
        - ./frontend/certs/frontend.key:/etc/apache2/server.key:ro
    environment:
        - ENV_DOCKER_REGISTRY_HOST=registry
        - ENV_DOCKER_REGISTRY_PORT=5000

