version: '3'
services:
  zookeeper:
    container_name: zookeeper 
    image: quay.io/debezium/zookeeper:1.9
    ports:
      - 2181:2181
      - 3888:3888
      - 2888:2888
  kafka:
    image: quay.io/debezium/kafka:1.9
    container_name: kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: quay.io/debezium/example-mysql:1.9
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on: [ kafka ]
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
     - zookeeper
     - kafka
  kafka-connect:
    image: quay.io/debezium/connect:1.9
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    