version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
      - "8083:8083"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./kafka:/opt/kafka
      # - ./connect-lib:/usr/share/java/kafka-connect-jdbc/
  # kafka-ui:
  #   image: obsidiandynamics/kafdrop:3.30.0
  #   depends_on: [ kafka ]
  #   ports:
  #     - "9000:9000"
  #   environment: 
  #     KAFKA_BROKERCONNECT: "kafka:29092"
  kafka-ui-2:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on: [ kafka ]
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
