version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=ROOTNAME"
      - "MINIO_ROOT_PASSWORD=CHANGEME123"
    volumes:
      - "./data:/data"
    command: "server /data  --console-address ':9090'"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3