---
http_interactions:
- request:
    method: get
    uri: http://registry.test.lan/v2/suse/busybox/manifests/digest
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - registry.test.lan
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Docker-Distribution-Api-Version:
      - registry/2.0
      Date:
      - Mon, 20 Apr 2015 10:06:19 GMT
      Content-Length:
      - '170'
    body:
      encoding: UTF-8
      string: |
        { "tag": "latest", "config": { "size": 1000 }, "layers": [] }
    http_version:
  recorded_at: Mon, 20 Apr 2015 10:06:19 GMT
