---
http_interactions:
- request:
    method: get
    uri: http://registry.test.lan/v2/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - registry.test.lan
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Docker-Distribution-Api-Version:
      - registry/2.0
      Www-Authenticate:
      - Bearer realm="http://portus.test.lan/v2/token",service="registry.test.lan"
      Date:
      - Mon, 20 Apr 2015 10:28:38 GMT
      Content-Length:
      - '114'
    body:
      encoding: UTF-8
      string: |
        {"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
    http_version: 
  recorded_at: Mon, 20 Apr 2015 10:28:38 GMT
recorded_with: VCR 2.9.3
