version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.30.0
    restart: always
    container_name: prometheus
    volumes:
      # config
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/:/etc/prometheus/
      # tsdb data
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # backup 
      - '--web.enable-admin-api'
      # tsdb time delete
      - '--storage.tsdb.retention.time=100d'
      # tsdb locat
      - '--storage.tsdb.path=/prometheus'
      # reload config
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
   
  grafana:
    image: grafana/grafana:8.1.5
    restart: always
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - ./node/proc:/host/proc:ro
      - ./node/sys:/host/sys:ro
      - ./node:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
       