FROM cytopia/ansible:latest-awshelm2.11

ARG ssh_prv_key
RUN apk add --update --no-cache openssh sshpass
RUN pip install requests google-auth
RUN pip install docker

COPY ./ ./

RUN ansible-playbook --version
RUN mkdir -p /tmp/.ansible/tmp
RUN mkdir -p /.ansible/tmp
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

RUN echo -n $ssh_prv_key | base64 -d > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa
