---
http_interactions:
- request:
    method: get
    uri: https://registry.mssola.cat/v2/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - application/vnd.docker.distribution.manifest.v2+json
      User-Agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Server:
      - nginx
      Date:
      - Thu, 03 Aug 2017 15:47:26 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Basic realm="Application"
      Cache-Control:
      - no-cache
      X-Request-Id:
      - d6e6ff71-6077-4797-b255-f806857fff9c
      X-Runtime:
      - '0.107929'
      Docker-Distribution-Api-Version:
      - 'registry/2.0'
    body:
      encoding: UTF-8
      string: '{"error":"You need to sign in or sign up before continuing."}'
    http_version:
  recorded_at: Thu, 03 Aug 2017 15:47:26 GMT
- request:
    method: get
    uri: http://registry.mssola.cat:6061/health
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - clair
      Date:
      - Thu, 03 Aug 2017 15:47:26 GMT
      Content-Length:
      - '0'
      Content-Type:
      - text/plain; charset=utf-8
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Thu, 03 Aug 2017 15:47:26 GMT
recorded_with: VCR 3.0.3
