---
http_interactions:
- request:
    method: get
    uri: https://registry.mssola.cat/v2/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - application/vnd.docker.distribution.manifest.v2+json
      User-Agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Server:
      - nginx
      Date:
      - Thu, 03 Aug 2017 15:36:22 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Www-Authenticate:
      - Basic realm="Application"
      Cache-Control:
      - no-cache
      X-Request-Id:
      - 9eed8ef5-8c52-4673-af54-afb6534925b0
      X-Runtime:
      - '0.190492'
      Docker-Distribution-Api-Version:
      - 'registry/2.0'

    body:
      encoding: UTF-8
      string: '{"error":"You need to sign in or sign up before continuing."}'
    http_version:
  recorded_at: Thu, 03 Aug 2017 15:36:22 GMT
recorded_with: VCR 3.0.3
