version: "3"
services:
  node:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused$
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
  explorer:
    image: alethio/ethereum-lite-explorer
    ports:
      - 8080:80
    
    environment:
      - APP_NODE_URL=http://localhost:8545