version: '3.1'
services:
  mongo:
    image: mongo:5.0.5
    restart: always
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db