version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo-server'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: 'mongo-ui'
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin